[project]
name = "20250327-auto-docstring-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.69.0",
    "openrouter>=1.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
